version: '4.0'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: room_service
    ports:
      - "5666:5432"
    volumes:
      - room_data:/var/lib/postgresql/data

volumes:
  room_data:


