version: '4.0'

services:
  finance_database:
    image: postgres:15
    container_name: finance_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finance_service
    ports:
      - "7666:5432"
    volumes:
      - finance_data:/var/lib/postgresql/data

  room_database:
    image: postgres:15
    container_name: room_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: room_service
    ports:
      - "5666:5432"
    volumes:
      - room_data:/var/lib/postgresql/data

  tenant_database:
    image: postgres:15
    container_name: tenant_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tenant_service
    ports:
      - "5777:5432"
    volumes:
      - tenant_data:/var/lib/postgresql/data

  auth_database:
    image: postgres:15
    container_name: auth_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_service
    ports:
      - "7777:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"

volumes:
  finance_data:
  room_data:
  tenant_data:
  auth_data:

