version: '4.0'

services:
  postgres:
    image: postgres:15
    container_name: postgres_tenant
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tenant_service
    ports:
      - "5777:5432"
    volumes:
      - tenant_data:/var/lib/postgresql/data
#      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  tenant_data:


